-- CreateEnum
CREATE TYPE "PurchaseStatus" AS ENUM ('PENDDING', 'APPROVED', 'FAILED');

-- AlterTable
ALTER TABLE "Purchase" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" "PurchaseStatus" NOT NULL DEFAULT E'PENDDING',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
